'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const http=require('node:http');const {startServer,PROTOCOL_VERSION}=require('../mcp_server');const {inspectDocx}=require('../docx_artifact');
const ROOT=path.resolve(__dirname,'..','..','..');
function sha(b){return crypto.createHash('sha256').update(b).digest('hex');}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'roa-e2e-'));fs.mkdirSync(path.join(root,'Operation','runner'),{recursive:true});fs.mkdirSync(path.join(root,'Operation','corpus','text'),{recursive:true});fs.mkdirSync(path.join(root,'.git','refs','heads'),{recursive:true});fs.copyFileSync(path.join(ROOT,'IKANT_ROA_ACCESS_CONTRACT.md'),path.join(root,'IKANT_ROA_ACCESS_CONTRACT.md'));fs.copyFileSync(path.join(ROOT,'Operation','iKANT_PROMPT.md'),path.join(root,'Operation','iKANT_PROMPT.md'));const source=Buffer.from('ROA sostiene che le rappresentazioni sono limitate e che le pretese devono restare ricostruibili.\n');fs.writeFileSync(path.join(root,'Operation','corpus','text','roa-main-entrypoint.md'),source);fs.writeFileSync(path.join(root,'Operation','MANIFEST.json'),JSON.stringify({pdfs:[{id:'roa-main-entrypoint',title:'ROA',role:'main_entrypoint',text_url:'https://raw.githubusercontent.com/Luke883i/ROA/main/Operation/corpus/text/roa-main-entrypoint.md',text_sha256:sha(source)}]}));const ref='a'.repeat(40);fs.writeFileSync(path.join(root,'.git','HEAD'),'ref: refs/heads/main\n');fs.writeFileSync(path.join(root,'.git','refs','heads','main'),ref+'\n');return root;}
function rpc(port,method,params={},name=null){return new Promise((resolve,reject)=>{const body=JSON.stringify({jsonrpc:'2.0',id:1,method,params});const headers={'content-type':'application/json','content-length':Buffer.byteLength(body),'mcp-protocol-version':PROTOCOL_VERSION,'mcp-method':method,host:'127.0.0.1'};if(name)headers['mcp-name']=name;const req=http.request({host:'127.0.0.1',port,path:'/mcp',method:'POST',headers},res=>{let d='';res.setEncoding('utf8');res.on('data',c=>d+=c);res.on('end',()=>resolve({status:res.statusCode,json:JSON.parse(d)}));});req.on('error',reject);req.end(body);});}
test('true local E2E: terms -> exact acceptance -> verified context -> finalize -> persisted/readback DOCX -> follow-up without ceremony',async()=>{const root=fixture();const started=await startServer({repoRoot:root,artifactDir:path.join(root,'artifacts','debug'),port:0});try{const port=started.port;const first=await rpc(port,'tools/call',{name:'ikant_turn',arguments:{message:'Spiegami ROA'}},'ikant_turn');assert.equal(first.status,200);const gate=first.json.result.structuredContent;assert.equal(gate.phase,'public');assert.ok(gate.continuation.startsWith('c_'));assert.equal(gate.artifact.kind,'TERMS');const terms=await rpc(port,'resources/read',{uri:gate.artifact.uri},gate.artifact.uri);assert.match(terms.json.result.contents[0].text,/iKANT™ — TERMS OF USE/);
const accepted=await rpc(port,'tools/call',{name:'ikant_turn',arguments:{continuation:gate.continuation,message:'I ACCEPT'}},'ikant_turn');const prep=accepted.json.result.structuredContent;assert.equal(prep.phase,'draft_required');assert.match(prep.context.sources[0].text,/rappresentazioni sono limitate/);
const final=await rpc(port,'tools/call',{name:'ikant_finalize',arguments:{continuation:gate.continuation,synthesis_token:prep.synthesis_token,voice:'ROA propone di trattare ogni risposta come una rappresentazione limitata, mantenendo visibili i vincoli che ne determinano l’uso.',terminal:'Answer',public_reasons:['Il testo verificato esplicita il limite delle rappresentazioni.'],falsifiers:['Una fonte canonica successiva può contraddire questa formulazione.'],backlog:['Confrontare il risultato con gli altri nodi quando la domanda lo richiede.']}},'ikant_finalize');const out=final.json.result.structuredContent;assert.equal(out.phase,'public');assert.match(out.voice,/rappresentazione limitata/);assert.equal(out.artifact.kind,'DOCX');assert.equal(out.artifact.readback_verified,true);const art=await rpc(port,'resources/read',{uri:out.artifact.uri},out.artifact.uri);const bytes=Buffer.from(art.json.result.contents[0].blob,'base64');const packet=inspectDocx(bytes).packet;assert.equal(packet.terminal,'Answer');assert.equal(packet.source_vector[0].id,'roa-main-entrypoint');assert.ok(packet.public_reasons.length);assert.ok(packet.falsifiers.length);assert.ok(packet.backlog.length);assert.match(packet.header,/NO PRIVATE CHAIN-OF-THOUGHT/);
const follow=await rpc(port,'tools/call',{name:'ikant_turn',arguments:{continuation:gate.continuation,message:'Approfondisci'}},'ikant_turn');assert.equal(follow.json.result.structuredContent.phase,'draft_required');assert.equal(follow.json.result.structuredContent.context.intent,'Approfondisci');}finally{await new Promise(r=>started.server.close(r));}});
