'use strict';
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const PROMPT_BEGIN='<!-- PROMPT:BEGIN -->',PROMPT_END='<!-- PROMPT:END -->';
function sha256(text){return crypto.createHash('sha256').update(Buffer.from(text,'utf8')).digest('hex');}
function field(text,key){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const m=text.match(new RegExp(`^${escaped}:\\s*(.+)$`,'m'));return m?m[1].trim():null;}
function extractPromptBody(text){if(text.split(PROMPT_BEGIN).length-1!==1)throw new Error('prompt-marker-begin-cardinality');if(text.split(PROMPT_END).length-1!==1)throw new Error('prompt-marker-end-cardinality');const segment=text.split(PROMPT_BEGIN)[1].split(PROMPT_END)[0];const m=segment.match(/^\n```text\n([\s\S]*)```\n$/);if(!m||!m[1].endsWith('\n'))throw new Error('prompt-body-envelope-invalid');return m[1];}
function promptVersion(text){const m=text.match(/`IKANT_PROMPT_VERSION:\s*([^`]+)`/);if(!m)throw new Error('prompt-version-missing');return m[1].trim();}
function declaredPromptSha(text){const m=text.match(/`IKANT_PROMPT_BODY_SHA256:\s*([0-9a-f]{64})`/);if(!m)throw new Error('prompt-declared-sha256-missing');return m[1];}
function loadOperatingPrompt(repoRoot){const root=path.resolve(repoRoot||path.resolve(__dirname,'..','..'));const contract=fs.readFileSync(path.join(root,'IKANT_ROA_ACCESS_CONTRACT.md'),'utf8');const promptRel=field(contract,'operating_prompt_path'),expectedVersion=field(contract,'operating_prompt_version'),expectedSha=field(contract,'operating_prompt_body_sha256');if(!promptRel||!expectedVersion||!expectedSha)throw new Error('contract-prompt-binding-missing');const text=fs.readFileSync(path.join(root,promptRel),'utf8');const body=extractPromptBody(text),version=promptVersion(text),got=sha256(body),declared=declaredPromptSha(text);if(version!==expectedVersion)throw new Error('prompt-version-drift');if(declared!==got)throw new Error('prompt-self-digest-mismatch');if(got!==expectedSha)throw new Error('prompt-contract-digest-mismatch');return Object.freeze({ok:true,prompt_path:promptRel,prompt_version:version,prompt_sha256:got,body,authority:0,authorizing:false});}
function makePromptLoadReceipt(binding,hostReadbackSha256,loadedAt=new Date().toISOString()){if(!binding||binding.ok!==true||!binding.body)throw new Error('prompt-binding-required');if(hostReadbackSha256!==binding.prompt_sha256)throw new Error('host-readback-mismatch');return Object.freeze({prompt_path:binding.prompt_path,prompt_version:binding.prompt_version,prompt_sha256:binding.prompt_sha256,prompt_loaded_at:loadedAt,host_readback_sha256:hostReadbackSha256,authority:0,authorizing:false});}
module.exports={sha256,field,extractPromptBody,promptVersion,declaredPromptSha,loadOperatingPrompt,makePromptLoadReceipt};
