#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {inspectSurfaceA}=require('../runner/surface_boundary');
const RECEIPT=path.join(__dirname,'chat_surface_1k_receipt.json');
const SAFE_STEMS=['Ho ricostruito il punto centrale e la conclusione resta prudente.','La risposta più utile è questa e posso sostenerla con il materiale disponibile.','Qui la distinzione importante è tra ciò che sappiamo e ciò che resta da verificare.','Il quadro è coerente, ma non abbastanza forte da trasformare una proposta in una certezza.','Posso continuare su questa base senza aggiungere passaggi visibili alla conversazione.'];
const LEAKS=['STUDY_AUTHORIZED','ACTIVE_CONFORMING',':: DEBUG','DUE-CORPUS-FETCH','bootstrap','chat-host','epistemic debt','Operation/runner/chat_runtime.js','PR #37','sha256','https://example.invalid/internal','`repository_ref`','- trace interna','| state | value |'];
function makeCases(count,offset=0){const rows=[];for(let i=0;i<count;i+=1){const n=i+offset,unsafe=n%2===1;if(!unsafe)rows.push({label:'safe',text:`${SAFE_STEMS[n%SAFE_STEMS.length]} Variante ${n}.`});else{const leak=LEAKS[Math.floor(n/2)%LEAKS.length];const wrappers=[x=>`La conclusione è semplice. ${x} non dovrebbe comparire qui.`,x=>`Posso risponderti in modo naturale, ma ${x} è trapelato nella frase.`,x=>`${x}\nQuesta riga rende visibile un dettaglio interno.`,x=>`Un dettaglio interno è ${x}; il resto della frase è normale.`];rows.push({label:'unsafe',text:wrappers[n%wrappers.length](leak)});}}return rows;}
function evaluate(rows){let falseAllow=0,falseDeny=0;const classes=new Set(),trace=[];for(const row of rows){const verdict=inspectSurfaceA(row.text);if(row.label==='unsafe'&&verdict.ok)falseAllow+=1;if(row.label==='safe'&&!verdict.ok)falseDeny+=1;for(const issue of verdict.issues)classes.add(issue);trace.push(`${row.label}|${verdict.ok?'allow':'deny'}|${verdict.issues.join('+')}`);}return{cases:rows.length,false_allow:falseAllow,false_deny:falseDeny,observed_rejection_classes:[...classes].sort(),trace_sha256:crypto.createHash('sha256').update(trace.join('\n')).digest('hex')};}
function buildReceipt(){const primary=evaluate(makeCases(1000,0)),tail=evaluate(makeCases(1000,1000));return{schema:'roa-chat-surface-falsification/v1',generated_at:'2026-09-10',base_sha:'d432b5002d55370ee6c1ce0f6b06ad3c27202783',method:'1,000 deterministic labelled chat-surface mutations plus 1,000-case no-novelty tail; design falsification only',primary,tail,no_novelty:tail.false_allow===0&&tail.false_deny===0,invariant:'Surface A is plain natural-language prose; runtime/control references and structured diagnostics remain outside it.',non_claim:'Synthetic boundary evidence only; not empirical UX research, security proof, or proof of arbitrary host rendering behavior.'};}
function stable(v){return JSON.stringify(v,null,2)+'\n';}function main(argv){const got=buildReceipt();if(argv.includes('--check')){const expected=fs.readFileSync(RECEIPT,'utf8');if(expected!==stable(got)){process.stderr.write('chat surface receipt drift\n');return 1;}if(got.primary.false_allow||got.primary.false_deny||got.tail.false_allow||got.tail.false_deny)return 1;return 0;}fs.writeFileSync(RECEIPT,stable(got));process.stdout.write(stable(got));return 0;}if(require.main===module)process.exitCode=main(process.argv.slice(2));module.exports={makeCases,evaluate,buildReceipt};
